name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      artifact-path: ${{ steps.build.outputs.artifact-path }}
    steps:
    - uses: actions/checkout@v4

    - name: Build the application
      run: |
        cd ./src
        make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: trispo-binary
        path: ./src/trispo

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download built binary
      uses: actions/download-artifact@v4
      with:
        name: trispo-binary
        path: ./src

    - name: Run tests
      run: |
        cd ./src
        make test

  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build, test]
    steps:
    - uses: actions/checkout@v4

    - name: Download built binary
      uses: actions/download-artifact@v4
      with:
        name: trispo-binary
        path: ./src

    - name: Package the application
      run: |
        mkdir -p deb-package/DEBIAN
        echo "Package: trispo" > deb-package/DEBIAN/control
        echo "Version: 5.2.4" >> deb-package/DEBIAN/control
        echo "Architecture: amd64" >> deb-package/DEBIAN/control
        echo "Maintainer: Pivonikl & Vodnik" >> deb-package/DEBIAN/control
        echo "Description: check prime num" >> deb-package/DEBIAN/control

        mkdir -p deb-package/usr/bin
        cp ./src/trispo deb-package/usr/bin/
        
        dpkg-deb --build deb-package trispo.deb

    - name: Upload the deb package as an artifact
      uses: actions/checkout@v4
      with:
        name: trispo-deb-package
        path: trispo.deb

    - name: GitHub release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: trispo.deb
        body: Pivo
        name: trispo-release
        tag: v5.2.4
        token: ${{ secrets.GITHUB_TOKEN }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: package

    env:
      DOCKER_IMAGE_NAME: poltoraxa
      DOCKER_CONTEXT_DIR: trspo
      DEB_ARTIFACT_NAME: trispo-release
      DEB_FILENAME: trispo.deb
      GIT_BRANCH: main
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}
  
      - name: Download .deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DEB_ARTIFACT_NAME }}
          path: .
  
      - name: Copy deb package to Docker context
        run: cp ${{ env.DEB_FILENAME }} ${{ env.DOCKER_CONTEXT_DIR }}/
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_CONTEXT_DIR }}
  
      - name: Run Docker container and test app
        timeout-minutes: 5
        run: |
          echo 3 | docker run -i --rm ${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
  
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
