name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Этап 1: Сборка приложения с помощью Makefile
    - name: Set up GCC and Make
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Build the application
      run: |
        cd ./src
        make

    # Этап 2: Тестирование программы
    - name: Run tests
      run: make test

    # Этап 3: Упаковка в .deb пакет
    - name: Build the deb package
      run: make deb

