name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Этап сборки
    - name: Build the application
      run: |
        cd ./src
        make 

    # Этап тестирования
    - name: Run tests
      run: |
        cd ./src
        make test
    
    # Этап упаковки в .deb
    - name: Package the application
      run: |
        mkdir -p deb-package/DEBIAN
        echo "Package: trispo" > deb-package/DEBIAN/control
        echo "Version: 5.2.0" >> deb-package/DEBIAN/control
        echo "Architecture: amd64" >> deb-package/DEBIAN/control
        echo "Maintainer: Pivonikl & Vodnik" >> deb-package/DEBIAN/control
        echo "Description: check prime num" >> deb-package/DEBIAN/control

        mkdir -p deb-package/usr/bin
        cp ./src/trispo deb-package/usr/bin/
        
        dpkg-deb --build deb-package trispo.deb

    - name: Upload the deb package as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: trispo-deb-package
        path: trispo.deb

    - name: Create GitHub release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifact: trispo.deb
        body: Release Notes
        name: trispo-release
        tag: v5.2.0
        token: ${{ secrets.GITHUB_TOKEN }}
