name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the application
      run: |
        cd ./src
        make 
        
    - name: Run tests
      run: |
        cd ./src
        make test
    
    - name: Package the application
      run: |
        mkdir -p deb-package/DEBIAN
        echo "Package: trispo" > deb-package/DEBIAN/control
        echo "Version: 5.2.0" >> deb-package/DEBIAN/control
        echo "Architecture: amd64" >> deb-package/DEBIAN/control
        echo "Maintainer: Pivonikl & Vodnik" >> deb-package/DEBIAN/control
        echo "Description: check prime num" >> deb-package/DEBIAN/control

        mkdir -p deb-package/usr/bin
        cp ./src/trispo deb-package/usr/bin/
        
        dpkg-deb --build deb-package trispo.deb

    - name: Upload the deb package as an artifact
      uses: actions/checkout@v4
      with:
        name: trispo-deb-package
        path: trispo.deb

    - name: GitHub release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: trispo.deb
        body: Pivo
        name: trispo-release
        tag: v5.2.0
        token: ${{ secrets.GITHUB_TOKEN }}
