name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install -y g++

    - name: Install Make
      run: sudo apt-get install -y make

    - name: Build the project
      run: |
        cd trspo/src
        make

    - name: Run tests
      run: |
        cd trspo/src
        make test
