name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd ./src
        make 
    - name: test
      run: |
        cd ./src
        make test
    - name: package
      run: |
        cd ..
        dpkg-deb --build package trispo.deb
    - name: create-release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifactErrorsFailBuild: true 
        artifact: ../trispo_5.2.0_amd64.deb  
        body: Pivonikl
        name: Pivondepula
        tag: Litryshka
        token: ${{ secrets.MY_SECRET_NAME }}
